# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Generate and publish AAR for Exo-Player"
  lane :build_n_publish_aar do |options|
    publish()
  end

  private_lane :publish do |options|
    gradle(task: "publishReleasePublicationToMavenRepository")
  end

end