/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package androidx.media3.decoder.hsdav1d;

public class HsDavidSwigGenerated {
  public static long hsdav1d_initialize_jni(int nThreads, HsDav1dJniLogger callback) {
  return HsDavidSwigGeneratedJNI.hsdav1d_initialize_jni(nThreads, callback);
}

  public static void hsdav1d_cleanup_jni(long c) {
    HsDavidSwigGeneratedJNI.hsdav1d_cleanup_jni(c);
  }

  public static int hsdav1d_send_input(long c, java.nio.ByteBuffer buffer, int length) {
    return HsDavidSwigGeneratedJNI.hsdav1d_send_input(c, buffer, length);
  }

  public static int hsdav1d_decode_process(long c, androidx.media3.decoder.VideoDecoderOutputBuffer jOutputBuffer, boolean isDecodeOnly) {
    return HsDavidSwigGeneratedJNI.hsdav1d_decode_process(c, jOutputBuffer, isDecodeOnly);
  }

  public static void hsdav1d_flush_decoder(long c) {
    HsDavidSwigGeneratedJNI.hsdav1d_flush_decoder(c);
  }

  public static int hsdav1d_render_output_frame(long c, android.view.Surface jSurface, androidx.media3.decoder.VideoDecoderOutputBuffer jOutputBuffer) {
    return HsDavidSwigGeneratedJNI.hsdav1d_render_output_frame(c, jSurface, jOutputBuffer);
  }

  public static void hsdav1d_release_output_frame(long c, androidx.media3.decoder.VideoDecoderOutputBuffer jOutputBuffer) {
    HsDavidSwigGeneratedJNI.hsdav1d_release_output_frame(c, jOutputBuffer);
  }

}
