name: Snapshot Release on PR Comment

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  snapshot-release:
    uses: "hotstar/hotstar-github-action-workflows/.github/workflows/hotstar-android-snapshot-release.yml@main"
    with:
      FILE: "constants.gradle"
      VAR_NAME: "version"
      JAVA_VERSION: 21
    secrets: inherit

  comment-version:
    needs:
      - snapshot-release
    runs-on: hs-releng-action-runner-ci
    steps:
      - name: Publish snapshot version in comment
        uses: mshick/add-pr-comment@v2
        with:
          message-id: ${{ needs.snapshot-release.outputs.VERSION_NAME }} # avoids updating previous comments
          message: |
            🚀 Snapshot version released: `${{ needs.snapshot-release.outputs.VERSION_NAME }}`

